---
- name: Configure MeetMux Web Servers
  hosts: webservers
  become: yes

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create custom landing page
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to MeetMux Production</h1>
          <p>Server Configured by Ansible Automation</p>

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes