name: Day4_Automation_Check

on: [push]

jobs:
  test_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Give permission
        run: chmod +x scripts/setup_server.sh

      - name: Run Setup Script
        run: bash scripts/setup_server.sh