name: Day4_Automation_Check

on: [push]

jobs:
  test_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Setup Script
        run: |
          chmod +x scripts/setup_server.sh
          ./scripts/setup_server.sh || true